name: approve check
on:
  pull_request_review:
    types: [submitted]
jobs:
  pr-automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name : Check Approve
        uses : 4835/pr_approve_check_action@1.0.6
        with:
          min-approval: 1
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name : Save PR number
        if: success()
        run  : |
          mkdir -p ./pr
          echo ${{ github.server_url }}/${{ github.repository }}/pull/$PR_NUMBER > ./pr/NR
        env :
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
